# Generated by Django 6.0.5 on 2026-05-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inquiry_title', models.CharField(blank=True, max_length=100, null=True)),
                ('inquiry_details', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, '未対応'), (1, '対応中'), (2, '対応済み')], default=0)),
                ('delete_flg', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.authority')),
                ('from_belong_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.shop')),
                ('from_belong_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_inquiries', to='accounts.authority')),
                ('to_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.relation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
