# Generated by Django 6.0.6 on 2026-06-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_inquirycategory_inquiry_inquiry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='inquiry.inquirycategory'),
        ),
    ]
