upstream djangopf {
    server web:8000;
}
server{
    listen       80 default_server;
    listen       [::]:80 default_server;
    charset     utf-8;
    client_max_body_size 20M;
    set $basic ${BASIC};
    set $auth off;
    if ( $basic = "true") {
        set $auth "Restricted";
    }
    if ( $basic = "false" ) {
        set $auth off;
    }
    if ($http_user_agent = "ELB-HealthChecker/2.0") {
        set $auth off;
    }
    location / {
        proxy_pass http://djangopf;
        proxy_set_header Host $http_host;
        auth_basic $auth;
        auth_basic_user_file  /etc/nginx/.htpasswd;
    }
    location /static {
        alias ${STATIC_DIR};
        add_header Cache-Control "${STATIC_CACHE_CONTROL}";
    }
    location /media {
        alias /app/media/;
    }
    location /react/ {
        ${REACT_LOCATION}
    }
}
server_tokens off;
