from django.urls import path
from inventory.views import (
    GoodsCategoryCreateView,
    GoodsCategoryDeleteView,
    GoodsCategoryListView,
    GoodsCategoryUpdateView,
    GoodsCreateView,
    GoodsDeleteView,
    GoodsListView,
    GoodsUpdateView,
    RelationConnectView,
    RelationCreateView,
    RelationDeleteView,
    RelationListView,
    ShopConnectedWarehouseListView,
    WarehouseCreateView,
    WarehouseDeleteView,
    WarehouseListView,
    WarehouseUpdateView,
    WarehouseStockListView,
    WarehouseStockEditView,
    ShopCreateView,
    ShopDeleteView,
    ShopDetailView,
    ShopListView,
    ShopUpdateView,
    ShopStockListView,
    ShopStockEditView,
    OrderGoodsListView,
    OrderCreateView,
    OrderCsvDownloadView,
    OrderCsvImportView,
    OrderHistoryView,
    OrderHistoryCSVExportView,
    OrderHistoryPDFExportView,
    WarehouseOrderListView,
    WarehouseOrderStatusUpdateView,
    WarehouseOrderCSVExportView,
    WarehouseOrderPDFExportView,
)

urlpatterns = [
    path('goods/categories/', GoodsCategoryListView.as_view(), name='goods_category_list'),
    path('goods/categories/create/', GoodsCategoryCreateView.as_view(), name='goods_category_create'),
    path('goods/categories/<int:pk>/edit/', GoodsCategoryUpdateView.as_view(), name='goods_category_edit'),
    path('goods/categories/<int:pk>/delete/', GoodsCategoryDeleteView.as_view(), name='goods_category_delete'),
    path('goods/', GoodsListView.as_view(), name='goods_list'),
    path('goods/create/', GoodsCreateView.as_view(), name='goods_create'),
    path('goods/<int:pk>/edit/', GoodsUpdateView.as_view(), name='goods_edit'),
    path('goods/<int:pk>/delete/', GoodsDeleteView.as_view(), name='goods_delete'),
    path('warehouses/', WarehouseListView.as_view(), name='warehouse_list'),
    path('warehouses/create/', WarehouseCreateView.as_view(), name='warehouse_create'),
    path('warehouses/<int:pk>/edit/', WarehouseUpdateView.as_view(), name='warehouse_edit'),
    path('warehouses/<int:pk>/delete/', WarehouseDeleteView.as_view(), name='warehouse_delete'),
    path('warehouses/stock/', WarehouseStockListView.as_view(), name='warehouse_stock_list'),
    path('warehouses/stock/<int:goods_pk>/edit/', WarehouseStockEditView.as_view(), name='warehouse_stock_edit'),
    path('warehouses/orders/', WarehouseOrderListView.as_view(), name='warehouse_order_list'),
    path('warehouses/orders/<int:pk>/status-update/', WarehouseOrderStatusUpdateView.as_view(), name='warehouse_order_status_update'),
    path('warehouses/orders/export/csv/', WarehouseOrderCSVExportView.as_view(), name='warehouse_order_csv_export'),
    path('warehouses/orders/export/pdf/', WarehouseOrderPDFExportView.as_view(), name='warehouse_order_pdf_export'),
    path('shops/connected-warehouses/', ShopConnectedWarehouseListView.as_view(), name='shop_connected_warehouse_list'),
    path('shops/', ShopListView.as_view(), name='shop_list'),
    path('shops/create/', ShopCreateView.as_view(), name='shop_create'),
    path('shops/<int:pk>/', ShopDetailView.as_view(), name='shop_detail'),
    path('shops/<int:pk>/edit/', ShopUpdateView.as_view(), name='shop_edit'),
    path('shops/<int:pk>/delete/', ShopDeleteView.as_view(), name='shop_delete'),
    path('shops/stock/', ShopStockListView.as_view(), name='shop_stock_list'),
    path('shops/stock/<int:goods_pk>/edit/', ShopStockEditView.as_view(), name='shop_stock_edit'),
    path('relations/', RelationListView.as_view(), name='relation_list'),
    path('relations/connect/', RelationConnectView.as_view(), name='relation_connect'),
    path('relations/create/', RelationCreateView.as_view(), name='relation_create'),
    path('relations/<int:pk>/delete/', RelationDeleteView.as_view(), name='relation_delete'),
    path('orders/goods/', OrderGoodsListView.as_view(), name='order_goods_list'),
    path('orders/create/<int:goods_pk>/', OrderCreateView.as_view(), name='order_create'),
    path('orders/download/csv/', OrderCsvDownloadView.as_view(), name='order_csv_download'),
    path('orders/import/csv/', OrderCsvImportView.as_view(), name='order_csv_import'),
    path('orders/history/', OrderHistoryView.as_view(), name='order_history'),
    path('orders/history/export/csv/', OrderHistoryCSVExportView.as_view(), name='order_history_csv_export'),
    path('orders/history/export/pdf/', OrderHistoryPDFExportView.as_view(), name='order_history_pdf_export'),
]
