# Generated by Django 6.0.5 on 2026-05-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField()),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('delete_flg', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.goods')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('count_date', 'shop', 'goods'), name='unique_summary')],
            },
        ),
    ]
