# Generated by Django 6.0.5 on 2026-05-14 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authority_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.authority'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, 'その他')], null=True),
        ),
    ]
