# Generated by Django 6.0.5 on 2026-05-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_user_authority_id_alter_user_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authority_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.authority'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, 'その他')]),
        ),
    ]
