# Generated by Django 6.0.5 on 2026-05-18 04:20

import inventory.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', inventory.models.CustomUserManager()),
            ],
        ),
    ]
