# Generated by Django 6.0.5 on 2026-06-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_relation_unique_active_warehouse_shop'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopstock',
            constraint=models.UniqueConstraint(fields=('shop', 'goods'), name='unique_shop_goods'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'goods'), name='unique_warehouse_goods'),
        ),
    ]
