# Generated by Django 6.0.5 on 2026-06-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_shopstock_unique_shop_goods_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_flg', False)), fields=('shop_name',), name='unique_active_shop_name'),
        ),
    ]
